---
title: "Cloze Project Data Analysis"
output: html_notebook
---

Load our packages
```{r}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(Rmisc))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ez))
suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(gridExtra))
```

Load and summarize the data. We also want to switch the data types of 
ClausePlacement and Location to categorical since they are just binary factors

```{r}
data <- read.csv('../data/PreprocessedData.csv')
data$ClausePlacement <- as.factor(data$ClausePlacement)
data$Location <- as.factor(data$Location)
summary(data)
```

Setting up our contrasts (is this right? lol)
```{r}
contrasts.Tri <- 
  matrix(c(1/2, 1/2,
           -1, 1), 
         ncol = 2) %>%
  t(.) %>%
  solve(.) %>%
  .[,2:2]

contrasts(data$ClausePlacement) <- contrasts.Tri
contrasts(data$Location) <- c(-.5,.5)

model_matrix <- model.matrix( ~ ClausePlacement * Location, data)

data$cp1 <- model_matrix[,2]
data$l1 <- model_matrix[,3]
summary(data)
```

Model
```{r}
model <- lmer(Response ~ 1 + cp1 * l1 +
                (1 + cp1 + l1 + cp1:l1|| Participant) + 
                (1 + cp1 * l1 + cp1:l1|| Item), 
              data=data, 
              REML=F,
              control = lmerControl(calc.derivs=FALSE), 
              na.action = na.omit)
summary(model)
```
